name: Frontend refresh and deploy

on:
  schedule:
    - cron: '0 4 * * *'   # 06:00 SAST (UTC+2)
    - cron: '0 7 * * *'   # 09:00 SAST
    - cron: '0 10 * * *'  # 12:00 SAST
    - cron: '0 13 * * *'  # 15:00 SAST
    - cron: '0 16 * * *'  # 18:00 SAST
    - cron: '0 19 * * *'  # 21:00 SAST
    - cron: '30 21 * * *' # 23:30 SAST
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build production app
        working-directory: ./frontend
        run: npm run build
        env:
          ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          MONTHLY_BUDGET: ${{ secrets.MONTHLY_BUDGET }}

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/dist' 
          clean: true

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4