name: Backend fetch and process
on:
  schedule:
    - cron: '45 3 * * *'   # 05:45 SAST
    - cron: '45 6 * * *'   # 08:45 SAST
    - cron: '45 9 * * *'   # 11:45 SAST
    - cron: '45 12 * * *'  # 14:45 SAST
    - cron: '45 15 * * *'  # 17:45 SAST
    - cron: '45 18 * * *'  # 20:45 SAST
    - cron: '15 21 * * *'  # 23:15 SAST

  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '!backend/package.json'

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'
      
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci
      
      - name: Build backend
        working-directory: ./backend
        run: npm run build
      
      - name: Run backend
        working-directory: ./backend
        env:
          INVESTEC_HOST: ${{ secrets.INVESTEC_HOST }}
          INVESTEC_CLIENT_ID: ${{ secrets.INVESTEC_CLIENT_ID }}
          INVESTEC_CLIENT_SECRET: ${{ secrets.INVESTEC_CLIENT_SECRET }}
          INVESTEC_API_KEY: ${{ secrets.INVESTEC_API_KEY }}
          TRANSACTIONAL_ACCOUNT_ID: ${{ secrets.TRANSACTIONAL_ACCOUNT_ID }}
          PRIME_SAVER_ACCOUNT_ID: ${{ secrets.PRIME_SAVER_ACCOUNT_ID }}
          PROFILE_ID: ${{ secrets.PROFILE_ID }}
          ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          EXCLUSION_CATEGORIES: ${{ secrets.EXCLUSION_CATEGORIES }}
          SALARY_DESCRIPTION: ${{ secrets.SALARY_DESCRIPTION }}
        run: npm start